name: ChunkClaim
description: Advanced chunk claiming that supports X-Server
version: '${version}'
main: info.preva1l.chunkclaim.ChunkClaim
api-version: '1.16'
database: true
softdepend:
  - WorldGuard
  - AdvancedServerZones

libraries:
  - 'org.mongodb:mongodb-driver:3.12.14'